#ifndef __CONFIG_H
#define __CONFIG_H

// #define CONFIG_TEST_NEON
// #define CONFIG_REPLAY_TRACE
#define CONFIG_NR_CS_ARGS_REQS 128
#define CONFIG_NR_CS_IO_REQS 2048
#define CONFIG_NR_CS_FILES 1024
#define CONFIG_CS_FILE_INDEX_DEFAULT_LEN 1024
#define CONFIG_CS_FILE_MAX_PENDING_REQS 128
#define CONFIG_NR_HOST_IO_REQS 65536

#define CONFIG_ENABLE_SNAPSHOT 1
#define CONFIG_ENABLE_NAND_EMULATION 1

#define CONFIG_NAND_SECTORS_PER_PAGE 4
#define CONFIG_NAND_PAGES_PER_BLOCK 256
#define CONFIG_NAND_LUNS_PER_CHANNEL 2
#define CONFIG_NAND_CHANNELS 8
#define CONFIG_NAND_OP_RATIO 0.07
#define CONFIG_NAND_READ_LATENCY 150000
#define CONFIG_NAND_PROG_LATENCY 175000
#define CONFIG_NAND_ERASE_LATENCY 0
#define CONFIG_GC_THRESHOLD 0.75
#define CONFIG_GC_THRESHOLD_HIGH 0.95
#endif
